package com.tk.myapp.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors - Material 3 Expressive
val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF21005D)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors - cohesive "ink + mint-teal" palette
val md_theme_dark_primary = Color(0xFF5BDBC4)
val md_theme_dark_onPrimary = Color(0xFF003730)
val md_theme_dark_primaryContainer = Color(0xFF005046)
val md_theme_dark_onPrimaryContainer = Color(0xFF79F8E0)
val md_theme_dark_secondary = Color(0xFFB1CCC5)
val md_theme_dark_onSecondary = Color(0xFF1C3531)
val md_theme_dark_secondaryContainer = Color(0xFF334B47)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E1)
val md_theme_dark_tertiary = Color(0xFFA9C7E8)
val md_theme_dark_onTertiary = Color(0xFF0D3050)
val md_theme_dark_tertiaryContainer = Color(0xFF274868)
val md_theme_dark_onTertiaryContainer = Color(0xFFCFE4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF889390)
val md_theme_dark_background = Color(0xFF0E1413)
val md_theme_dark_onBackground = Color(0xFFDEE4E1)
val md_theme_dark_surface = Color(0xFF0E1413)
val md_theme_dark_onSurface = Color(0xFFDEE4E1)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_inverseSurface = Color(0xFFDEE4E1)
val md_theme_dark_inverseOnSurface = Color(0xFF2B322F)
val md_theme_dark_inversePrimary = Color(0xFF006B5C)
val md_theme_dark_surfaceTint = Color(0xFF5BDBC4)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)

// Dark tonal surfaces - Material 3 surface containers for layered elevation
val md_theme_dark_surfaceBright = Color(0xFF343A38)
val md_theme_dark_surfaceDim = Color(0xFF0E1413)
val md_theme_dark_surfaceContainerLowest = Color(0xFF090F0E)
val md_theme_dark_surfaceContainerLow = Color(0xFF161D1B)
val md_theme_dark_surfaceContainer = Color(0xFF1A211F)
val md_theme_dark_surfaceContainerHigh = Color(0xFF252B29)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2F3634)
